"use client";

import Link from "next/link";
import { ArrowLeft, Printer } from "lucide-react";

/**
 * F11 — a print-beautiful weekly plan for the fridge / LA records. Renders the
 * approved plan (child first name, week-of date, per-day subject + topic + the
 * data-grounded reason) with a clean `@media print` stylesheet; "Save as PDF"
 * uses the browser's print-to-PDF (no PDF library — same pattern as the mastery
 * certificate + monthly report). No child PII beyond the first name.
 */

export interface PrintDay {
  label: string;
  items: { subject: string; topicTitle: string; reason?: string }[];
}

export function SchedulePrintView({
  firstName,
  weekLabel,
  days,
  approved,
}: {
  firstName: string;
  weekLabel: string;
  days: PrintDay[];
  approved: boolean;
}) {
  return (
    <div className="sched-root min-h-screen bg-void px-6 py-10 print:bg-white print:px-0 print:py-0">
      <style>{`
        @media print {
          .sched-noprint { display: none !important; }
          .sched-paper { box-shadow: none !important; background: #fff !important; color: #14110E !important; max-width: none !important; margin: 0 !important; border: none !important; }
          .sched-paper * { color: #14110E !important; }
          .sched-row { border-color: #E5E0D8 !important; break-inside: avoid; }
          @page { size: portrait; margin: 16mm; }
        }
      `}</style>

      <div className="sched-noprint mx-auto mb-6 flex max-w-3xl items-center justify-between">
        <Link
          href="/schedule"
          className="inline-flex items-center gap-2 text-sm text-fog-300 hover:text-fog-100"
        >
          <ArrowLeft className="h-4 w-4" /> Back to schedule
        </Link>
        <button
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-br from-violet-500 to-violet-700 px-4 py-2 text-sm font-medium text-white"
        >
          <Printer className="h-4 w-4" /> Print / Save as PDF
        </button>
      </div>

      <article className="sched-paper mx-auto max-w-3xl rounded-3xl border border-white/10 bg-white/[0.03] p-10 shadow-2xl print:rounded-none">
        <header className="mb-8 border-b border-white/10 pb-6 text-center">
          <p className="text-xs font-mono uppercase tracking-[0.3em] text-violet-300">
            Edway · weekly learning plan
          </p>
          <h1 className="mt-3 text-3xl font-semibold text-fog-50">
            {firstName}&apos;s week
          </h1>
          <p className="mt-1 text-sm text-fog-400">
            Week of {weekLabel}
            {approved ? " · approved by parent" : " · draft (not yet approved)"}
          </p>
        </header>

        {days.length === 0 ? (
          <p className="py-8 text-center text-sm text-fog-400">
            No lessons are planned this week yet.
          </p>
        ) : (
          <div className="flex flex-col gap-5">
            {days.map((day) => (
              <section key={day.label} className="sched-row rounded-2xl border border-white/10 p-5">
                <h2 className="mb-3 text-lg font-semibold text-fog-50">{day.label}</h2>
                <ul className="flex flex-col gap-3">
                  {day.items.map((item, i) => (
                    <li key={i} className="flex flex-col gap-0.5">
                      <div className="flex items-baseline gap-2">
                        <span className="text-xs font-mono uppercase tracking-wider text-violet-300">
                          {item.subject}
                        </span>
                        <span className="text-base font-medium text-fog-100">
                          {item.topicTitle}
                        </span>
                      </div>
                      {item.reason && (
                        <p className="text-sm text-fog-400">{item.reason}</p>
                      )}
                    </li>
                  ))}
                </ul>
              </section>
            ))}
          </div>
        )}

        <footer className="mt-8 border-t border-white/10 pt-5 text-center">
          <p className="text-xs text-fog-500">
            Generated by Edway — a planned record of provision for {firstName}.
          </p>
        </footer>
      </article>
    </div>
  );
}
